### ISSUE TITLE
close button fixed

### ISSUE THREAD

**Issue by chiefjester** [qimingweng/react-modal-dialog#1]
Hi, wonderful library, any chance you can show me how to have a fixed header or close button, 
Use case: For long forms its always good that you have the close button visible all the time.

**Comment by qimingweng** [comment]
@deezahyn That's a good point, you would need to replace the ModalDialog component with a slightly diffrent one that either has a position: fixed close button or a onScroll handler which repositions the close button.

However, the solution I go with is usually to put a height restricted scroll area **within** a dialog. You could make the height restriction dynamic based on the screen height too.

**Comment by chiefjester** [comment]
how about how bootstrap uses their modal?  Where you can specify a fixed header and footer of the dialog.

**Comment by qimingweng** [comment]
@deezahyn That's an interesting suggestion. You can replace the `ModalDialog` class with whatever dialog implementation you want, really. I don't have time to do this now but if you submit a PR with another implementation I'd be happy to merge it.

**Comment by qimingweng** [comment]
I'm going to close this issue for now since it's not one of the goals of `react-modal-dialog` to be opinionated about how the dialog is shown
