### ISSUE TITLE
Disable body scroll when modal is open

### ISSUE THREAD

**Issue by onurhb** [qimingweng/react-modal-dialog#13]
This feature would be cool.

**Comment by qimingweng** [comment]
What does this mean?

**Comment by onurhb** [comment]
When the modal is active. The user is still able to scroll the page. 
Try scrolling, you'll see the page scroll behind the modal.

**Comment by qimingweng** [comment]
@onurmhb Any suggestions on how to turn that off?

**Comment by edrpls** [comment]
@qimingweng the modal could add a class to the body with overflow-y: hidden

**Comment by vsubbotskyy** [comment]
I suggest to toggle css class on body when modal is being opened or closed. We can than use @edrpls solution in our own code.
I created a PR:
https://github.com/qimingweng/react-modal-dialog/pull/36

**Comment by IveSix** [comment]
yep overflow hidden and height on body, but we dont' want to scroll top when modal is open, any solution?
