### ISSUE TITLE
Uncaught TypeError: Cannot read property 'refs' of null

### ISSUE THREAD

**Issue by gasipari** [qimingweng/react-modal-dialog#18]
Hi,
I am getting `Uncaught TypeError: Cannot read property 'refs' of null` when I close a dialog that has a form inside of it. If I remove the "ref" property of all input fields, then no error. But still need access to the fields input value via `refs.value`

It looks that the error is triggered in ModalBackground.js line 46.

Any idea on how to get rid of that error ?

Thanks,
Marius

**Comment by qimingweng** [comment]
@gasipari can you make a small demo with this error?

**Comment by gasipari** [comment]
sure.
- child component

```
  <ModalContainer onClose={this.props.onClose}>
  <ModalDialog onClose={this.props.onClose} style={{width: "50%"}}>
    {renderTitle()}
    <form onSubmit={this.handleFormSubmit}>
        <input type="text" id="name" ref="name" placeholder="Enter a name.." required/>
        <input type="text" id=“email” ref="email" placeholder="Enter an email..” required/>
    </form>
  </ModalDialog>
</ModalContainer>
```
- close handler in parent component, 

```
    handleClose: function () {
        this.setState({
            isShowingModal: false
        });
    },
```

**Comment by gasipari** [comment]
@qimingweng I found a workaround for this. Use ref in different way:

replace
`<input type="text" id="name" ref="name" placeholder="Enter a name.." required/>`
 with
  `<input type="text" id="name" ref={(ref) => this.name = ref} placeholder="Enter a name.." required/>`

then access the value with
`this.name.value` instead of `this.refs.name.value`

**Comment by qimingweng** [comment]
@gasipari glad you found a workaround, where did you access refs in the previous version of your code?

**Comment by gasipari** [comment]
@qimingweng I used `this.refs.name.value`

**Comment by qimingweng** [comment]
@gasipari The key is in which lifecycle method?

**Comment by mduheaume** [comment]
@gasipari Thanks for the workaround. It solved a problem for me too.

@qimingweng The error is triggered in the `componentWillUnmount` lifecycle method of ModalPortal.js (https://github.com/qimingweng/react-modal-dialog/blob/master/src/ModalPortal.js#L36)

**Comment by qimingweng** [comment]
I think these ref problem might be solved by doing `ref={(r) => this.something = r}` vs the string ref method
