### ISSUE TITLE
Allow width to be overwritten by user style 

### ISSUE THREAD

**Issue by Agamennon** [qimingweng/react-modal-dialog#2]
Thanks for this, its an awesome component! I would like to suggest that the width of the component be allow to be overwritten by the users style prop or stylesheet,  as the 500px might no be ideal for everyone

**Comment by qimingweng** [comment]
Hmm, that's a good idea; I'd need to move the default style over to a stylesheet though.

For now maybe the !important flag will do it for you.

**Comment by qimingweng** [comment]
Oh and by the way you can pass `width` as a property to the `ModalDialog` component

**Comment by ijidau** [comment]
Can I suggest a maxWidth property or, by default set the CSS max-width to 100%. This would make it handle mobile/responsive in a basic sense.

**Comment by qimingweng** [comment]
This is interesting, I think the goal is to provide a very unopinionated way to have a modal container and dialog; I night make a few different modal dialog components that users can choose from to achieve everybody's desired level of customizability

**Comment by ijidau** [comment]
By setting a fixed with already, the dialog is somewhat opinionated, so why not set a basic max-width: 100%? This would solve the responsive considerations as a simple default.

**Comment by qimingweng** [comment]
@ianjonesidau yes I just wish I could find like a 3 hour chunk of time to work on some of this; happy to take a PR

**Comment by qimingweng** [comment]
Although to be fair the dialog is sort of supposed to be opinionated; the Container tries not to be and (unfortunately still kind of is)

**Comment by qimingweng** [comment]
Ok, you should be able to overwrite the width with a style object now
