### ISSUE TITLE
react 15.2.0 introduces prop warnings

### ISSUE THREAD

**Issue by ssilve1989** [qimingweng/react-modal-dialog#20]
Updating to react 15.2.0 brings along this **loud** warning in the console.

`warning.js?8a56:44 Warning: Unknown props 'componentIsLeaving', 'top', 'left', 'recenter' on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop`

**Comment by ghost** [comment]
Did you get around it anyway ? I am having the same warning as well. The modal does not show up once this comes up.

**Comment by ssilve1989** [comment]
@ssbiswal1987 I haven't tried to modify the component, since it does still render for me.

**Comment by qimingweng** [comment]
See #21 for a potential solution, waiting on a few things there

This shouldn't affect the actual rendering - react tends to deprecate things slowly

**Comment by qimingweng** [comment]
Should be fixed in 3.0.2 @rvanmil
