### ISSUE TITLE
ios(iphone, ipad) background is not clickable

### ISSUE THREAD

**Issue by yevgnenll** [qimingweng/react-modal-dialog#25]
i made web page for mobile device page using react

all ios(ipad, iphone) modal popup background is not clickable

(desktop safari hasn't this issue)

after clicking modal is not closed

what is problem?

**Comment by qimingweng** [comment]
It might have to do with the click vs mousedown handler that react-modal-dialog is using

**Comment by yevgnenll** [comment]
@qimingweng could you explain more?
if i could fix i will send PR
you mean both are used in this?

**Comment by qimingweng** [comment]
Closed in #26
