### ISSUE TITLE
React dependency

### ISSUE THREAD

**Issue by ppershing** [qimingweng/react-modal-dialog#3]
In `package.json` react should probably be marked as a `peerDependency` not a `dependency`. This makes a big difference as currently `react-modal-dialog` library pulls its own version of `react` and react does not like to be double-imported.

**Comment by qimingweng** [comment]
Yes you're right this was an oversight on my part, I'll try to get to it ASAP

**Comment by qimingweng** [comment]
This is fixed in #v1.0.0
