### ISSUE TITLE
prevent closing when clicking on container but not on dialog

### ISSUE THREAD

**Issue by cordoval** [qimingweng/react-modal-dialog#41]
container seems to spawn the full width of the screen
when clicking on this area, the modal goes away
how to prevent this from happening? any quick option

**Comment by cordoval** [comment]
found a bug and here is the fix https://github.com/qimingweng/react-modal-dialog/pull/42

**Comment by wujiang1900** [comment]
Nice job!
I think this fix should be merged.
Thank you,
John Wu

**Comment by cordoval** [comment]
@qimingweng ping, i tried to replace my own make of Modal to keep going but it seems i do not know how to build it correctly since it requires other libraries and it ends up being a mess, so please let me know if this can be merged. Thanks

**Comment by qimingweng** [comment]
Let's move the convo to #42
