### ISSUE TITLE
Modal is positioned at the bottom of the page

### ISSUE THREAD

**Issue by Olgagr** [qimingweng/react-modal-dialog#46]
I added modal to my component:

```
return (
      <div>
        <div>
          {
            this.state.isShowingModal &&
            <ModalContainer onClose={this.handleClose.bind(this)}>
              <ModalDialog onClose={this.handleClose.bind(this)}>
                <h1>Dialog Content</h1>
                <p>More Content. Anything goes here</p>
              </ModalDialog>
            </ModalContainer>
          }
        </div>
        <Header />
        <div className="container">
          <SearchBox />
          <LabelForm />
          {this.renderRepos()}
        </div>
      </div>
```

However, when I open it, ModalDialog gets wrong value of topOffset. In my case it gets 3232.5px which puts it at the bottom of the page.

<img width="576" alt="repos_arranger" src="https://cloud.githubusercontent.com/assets/1297219/24079366/ad795922-0c86-11e7-9605-b953d3feb13b.png">

I the code I see that this value is injected by centerComponent. Should I pass something to make it work correctly ?

**Comment by Olgagr** [comment]
Ok, I found the issue. I didn't have doctype declaration in HTML file. In this case documentElement and body actually switch, so centerComponent returns wrong value.

**Comment by qimingweng** [comment]
I see... I've been using the UnstyledFlexDialog myself - if you want to look into that. It uses flexbox instead. It's much more reliable.
